#!/bin/bash
#SBATCH --account=def-cottenie
#SBATCH --job-name=checkv_phages
#SBATCH --time=01:00:00
#SBATCH --mem=8G
#SBATCH --cpus-per-task=4
#SBATCH --array=1-47
#SBATCH --output=/scratch/mogakwu/binf_6999_2026/checkv_logs/checkv_%A_%a.out
#SBATCH --error=/scratch/mogakwu/binf_6999_2026/checkv_logs/checkv_%A_%a.err

#Load apptainer
module load StdEnv/2023
module load apptainer/1.4.5

#Paths
BASEDIR=/scratch/mogakwu/binf_6999_2026
CHECKV=$BASEDIR/checkv.sif
CHECKVDB=$BASEDIR/checkv_db/checkv-db-v1.2
PHAGE_DIR=$BASEDIR/phages
OUTDIR=$BASEDIR/checkv_results
mkdir -p $OUTDIR

#Get the sample for this array task
FASTA=$(ls $PHAGE_DIR/*.fasta | sed -n "${SLURM_ARRAY_TASK_ID}p")
SAMPLE=$(basename $FASTA .fasta)

echo "[START] Running CheckV on $SAMPLE"

#Run CheckV
apptainer exec $CHECKV checkv end_to_end \
    $FASTA \
    $OUTDIR/${SAMPLE} \
    -d $CHECKVDB \
    -t 4

#Check success
if [[ $? -eq 0 ]]; then
    echo "[SUCCESS] CheckV completed for $SAMPLE"
else
    echo "[ERROR] CheckV failed for $SAMPLE"
    exit 1
fi

echo "[DONE] $SAMPLE finished"
